eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:48761/eureka/
server:
  port: 40216
spring:
  application:
    name: goods
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall
    initialSize: 1
    maxActive: 3
    maxPoolPreparedStatementPerConnectionSize: 2000
    maxWait: 60000
    minEvictableIdleTimeMillis: 90000
    minIdle: 2
    password: jytc84922927!
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 6000
    type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://139.9.239.198:3306/xj_maillist?characterEncoding=utf8
    url: jdbc:mysql://139.9.239.198:3306/xj_maillist?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    ValidationQuery: select * from user
mybatis:
  typeAliasesPackage: io.github.wangrangzhi.goods.mapper
  mapperLocations: classpath:mapper/*.xml
logging:
    level:
        io.github.wangrangzhi.goods.mapper: debug